name: test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up
        run: pip3 install -r requirements-dev.txt

      - name: Run tests
        run: pytest